# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    prefix      = "dev"
    bucket      = "secure-bucket-tfstate-composer"
    credentials = "service_account.json"
  }
}
