# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "simple-dreams-secure-bucket-tfstate-composer"
    credentials = "service_account.json"
    prefix      = "dev"
  }
}
