# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.34.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 3.34.0"
    }
  }
  required_version = ">= 0.13"
}
