# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "<4.0,>= 2.12"
    }
    google-beta = {
      source = "hashicorp/google-beta"
      version = "<4.0,>= 2.12"
    }
  }
  required_version = ">= 0.13"
}
