---
name: Checkov-Terraform Security Checks
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    name: Checkov Setup and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Security Test-terragrunt_infrastructure_modules, Skip Specific Tests
        run: |
          checkov -d terragrunt_infrastructure_modules --skip-check CKV_GCP_26,CKV_GCP_32,CKV_GCP_38,CKV2_GCP_3
      - name: Security Test-terraform_simple_setup, Skip Specific Tests
        run: |
          checkov -d terraform_simple_setup --skip-check CKV_GCP_26,CKV_GCP_32,CKV_GCP_38,CKV2_GCP_3
